--- # Install nginx
- name: Install nginx
  hosts: 10.124.0.3
  tasks:
  - name: add epel-release repo
    yum:
      name: epel-release
      state: latest
  - name: install nginx
    yum: name=nginx state=latest
  - name: start nginx
    service:
      name: nginx
      state: started
 
