---
- name: Name of the play
  hosts: localhost
  tasks:
  - name: Update yum rep
    yum: # module
      name: '*'
      state: latest
    yum:
  - name: Install reps
    yum:
      name:
        - vim
        - curl
        - wget
        - tree
      state: latest
